### ISSUE TITLE
Use Upstart service Provider on Ubuntu

### ISSUE THREAD

**Issue by svanzoest** [svanzoest-cookbooks/apache2#189]
See #151 and #150 for some background. 

Related to https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/689454

Chef reverted changing the default service provider to Upstart for >= 13.10 during regression; as this broke many packages without upstart scripts. See opscode/chef#1587

**Comment by svanzoest** [comment]
I tempted to remove the `provider` section in the service block and just let chef-client handle this, however we had #151 which added d42349dca3a24373141375cee49ab044fd468ff8 So, we will need to test if this is still an issue with chef 12 client or determine when this got fixed and require a chef version newer then that bug fix.

**Comment by drpebcak** [comment]
Perhaps we could look into adopting something like [this](https://github.com/poise/poise-service)?

**Comment by svanzoest** [comment]
@drpebcak possibly, but that should be new issue.

**Comment by drpebcak** [comment]
I just mentioned it because it relates. Also with #335.

**Comment by svanzoest** [comment]
I am going to close this, as we have cleaned the provider a lot based on other issues and ultimately, chef-client should manage this for us.
