### ISSUE TITLE
Need support for support for different versions of SuSE

### ISSUE THREAD

**Issue by rednevals** [svanzoest-cookbooks/apache2#190]
[FYI: This was done using the latest from the COOK-3900 branch ]

I am using SuSE 11 SP3. The testing that has been done on 13 SP3(I  think) has uncovered some basic differences in the layout/config of the initial apache2 installation. Certain assumptions are being made by the default recipe as to what is present and/or needed in the file system. I repeatedly stopped/started apache2 and attempted to address each error. These are the manual steps that I performed in order to get my Gerrit installation working:

================================
Created and/or modified files:
  Ones that httpd.conf is trying to load, but where missing.
  Deleted by ../cookbooks/apache2/recipes/default.rb:131

[ Created using touch ]...
/etc/apache2/uid.conf
/etc/apache2/listen.conf
/etc/apache2/mod_log_config.conf
/etc/apache2/mod_status.conf
/etc/apache2/mod_info.conf
/etc/apache2/mod_usertrack.conf
/etc/apache2/mod_autoindex-defaults.conf
/etc/apache2/errors.conf

================================
Existing files edited...
/etc/apache2/ports.conf
  # NameVirtualHost *:80

/etc/apache2/default-server.conf
  ???(forgot what I changed if anything...)

================================
Created dirs:
/etc/apache2/mods-available
/etc/apache2/mods-enabled
/etc/apache2/vhosts.d
/var/run/httpd

================================
New files edited:
/etc/apache2/mods-enabled/authz_default.load
  LoadModule authz_core_module /usr/lib64/apache2/mod_authz_core.so

How can this be addressed? Do we need version specific templates for SuSE?

**Comment by svanzoest** [comment]
please re-open or provide a PR, as it is unclear as to what needs to be done here.
