### ISSUE TITLE
COOK-1460: Default Ports Attribute can cause daemon restarts on every Chef run 

### ISSUE THREAD

**Issue by svanzoest** [svanzoest-cookbooks/apache2#216]
Migration of https://tickets.opscode.com/browse/COOK-1460 by Greg Albrecht 
plunk Internal JIRA: http://jira.splunk.com/browse/STORM-4670

To Reproduce

1. Add apache2 Cookbook Version 1.1.13 to Run List.
2. Add apache2::mod_ssl Cookbook Version 1.1.13 to Run List.
3. Run Chef.
Expected Results

1. Apache Daemon (httpd) should be configured and started with SSL support listening on ports 80 and 443.
Actual Results

1. Apache Daemon (httpd) is configured and started with SSL support listening on ports 80 and 443.
2. Apache Daemon (httpd) is restarted on every Chef run.
Logs

The following, sans the specific hashes, happens on every chef-client run:

[Mon, 16 Jul 2012 00:29:30 +0000] DEBUG: Processing template[/etc/apache2/ports.conf] on i-744c8b0c 
[Mon, 16 Jul 2012 00:29:30 +0000] INFO: Processing template[/etc/apache2/ports.conf] action create (apache2::mod_ssl line 34) 
[Mon, 16 Jul 2012 00:29:30 +0000] DEBUG: Not fetching cookbooks/apache2/templates/default/ports.conf.erb, as the cache is up to date. 
[Mon, 16 Jul 2012 00:29:30 +0000] DEBUG: current checksum: 09ed7d522079615834a13990bdef2542; manifest checksum: 09ed7d522079615834a13990bdef2542) 
[Mon, 16 Jul 2012 00:29:30 +0000] DEBUG: Current content's checksum: ad54abe48c13c43185ae8bbba10a7e4fe1d7b6bb1cfdc765b3ff7759d27e4bb3 
[Mon, 16 Jul 2012 00:29:30 +0000] DEBUG: Rendered content's checksum: 905920c300cb9a1bdc2850cb660be80ee3a39e22fa41930c03411a2eeb237433
[Mon, 16 Jul 2012 00:29:30 +0000] INFO: template[/etc/apache2/ports.conf] backed up to /var/chef/backup/etc/apache2/ports.conf.chef-20120716002930 
[Mon, 16 Jul 2012 00:29:30 +0000] INFO: template[/etc/apache2/ports.conf] mode changed to 644 
[Mon, 16 Jul 2012 00:29:30 +0000] INFO: template[/etc/apache2/ports.conf] updated content 
[Mon, 16 Jul 2012 00:29:30 +0000] INFO: template[/etc/apache2/ports.conf] not queuing delayed action restart on service[apache2] (delayed), as it's already been queued

Recipes

Here's the recipe we're using:

include_recipe 'apache2' 
include_recipe 'apache2::mod_ssl'

Work Around

Add ['apache']['listen_ports'] = ['80', '443'] to a Node's Override Attributes.

**Comment by drpebcak** [comment]
This doesn't happen anymore!
