### ISSUE TITLE
Apached 2.2 & mpm_xxx

### ISSUE THREAD

**Issue by fdutheil** [svanzoest-cookbooks/apache2#241]
I was "tuning" some mpm_prefork variables using env/attributes when I noticed that nothing was produced/taken in account (CentOS 6.5 & apache 2.2).
```
if node['apache']['version'] == '2.4' && !platform_family?('freebsd')
  # on freebsd the prefork mpm is staticly compiled in
  include_recipe "apache2::mpm_#{node['apache']['mpm']}"
end
```
Oh, well, the problem is a bit more complex for apache 2.2 on rhel: the .load file is not required as it is not a separate module. So the recipe mpm_prefork.erb can't indeed be the entry point.
I don't see any easy way to hack the actual apache2 cookbook to get it to use mpm related attributes to be taken into account.
As for v2.0.0 of the cookbooks, mpm attributes and apache 2.2 are broken.

**Comment by svanzoest** [comment]
Hi @acoulton Such a recipe update PR would be accepted. Although, for consistency, maybe we should use `load` instead of `loadmodule?` to match `conf`?

**Comment by jeffmacdonald** [comment]
Is the the same issue or is it different from : The docs say that mpm_prefork is the default for this cookbook, but a barebones install of it uses mpm_event ?

**Comment by svanzoest** [comment]
@jeffmacdonald you are referring to something unrelated.

 The default is indeed prefork, but based on platform detection we make assumptions on what the platform provided will have enabled and default to that. MPM switching is not something that is currently well supported. See the attributes for what the default MPM would be on your platform.

**Comment by jeffmacdonald** [comment]
Yeah. Its a pain in the butt at least for me as a chef noob. So many things depend upon this cookbook, including things that use PHP. But then it tells you PHP needs to be recompiled to support the MPM Event handler etc. Oh well. Can't complain. its free :)

**Comment by svanzoest** [comment]
If you add `apache2::mod_php5` it should try to switch your mpm to a
compatible one. What platform and version are you on?

**Comment by isbaran** [comment]
Hello,
I think its not restricted to centos, i'm using mpm worker on ubuntu 12.04 and also had to comment the .load file.
Fyi, conf directives are wrong too, MaxRequestWorkers and MaxConnectionsPerChild are not recognized (Apache/2.2.22)

**Comment by jeffmacdonald** [comment]
Its all good now. I included apache2::mod_php5 and it worked fine :). This was on Ubuntu 14.04. I think where I ran into issues was using Cacti which tries to install php on its own or something. Anyways, all good now.

**Comment by svanzoest** [comment]
@isbaran the conf directives change between Apache 2.2 and Apache 2.4 and the cookbook should translate the attributes for that. See for example in the [prefork mpm configuration template](https://github.com/svanzoest-cookbooks/apache2/blob/v3.0.1/templates/default/mods/mpm_prefork.conf.erb#L24-L25).

**Comment by svanzoest** [comment]
This issue got a lot of different related topics in it and therefore it is hard to keep track of what the actual issue is. I have created #354 to track the specific issue of the mpm attributes not being loaded into apache pre-apache 2.4 referencing this ticket for completeness.

Please open any new issues referencing this one if I missed one.
