### ISSUE TITLE
Make "httpd-devel" package name configurable

### ISSUE THREAD

**Issue by aik099** [svanzoest-cookbooks/apache2#285]
Current the `httpd` package name can be configured via `node[:apache][:package]` and that is good. But if somebody will use `httpd24` package, then this would create conflict on `httpd-devel` package install.

I propose to add new `default[:apache][:devel_package]` attribute with `httpd-devel` value and it. Then no conflict will happen during package installation stage.

Related issue: aws/opsworks-cookbooks#242

**Comment by drpebcak** [comment]
Fixed the httpd-devel issue.
