### ISSUE TITLE
Missing "libphp5.so" when using Remi repo

### ISSUE THREAD

**Issue by aik099** [svanzoest-cookbooks/apache2#287]
Decision to install `php` package is made based on fact, that php executable is missing. But php executable is provided by `php-cli` package, not `php` package: https://github.com/viverae-cookbooks/apache2/blob/master/recipes/mod_php5.rb#L37

I think that package install condition needs to be changed to assert presence of Apache php module instead.

This results in missing apache module file + enabled in configuration when the Remi repository is used to install php.

Related aws/opsworks-cookbooks#244

**Comment by drpebcak** [comment]
I took the milestone out because this doesn't really have anything to do with Amazon Linux (correct me if I'm wrong).

**Comment by svanzoest** [comment]
Seems like #339 is related to this.

**Comment by svanzoest** [comment]
Is this still an issue with our current maser and upcoming release?

**Comment by aik099** [comment]
I don't know. I no longer use AWS OpsWorks.

**Comment by svanzoest** [comment]
Thanks for the response.
I am going to close this, but if this is still an issue, please do not hesitate to open a new issue/PR.
