### ISSUE TITLE
apache conf.d directory deleted by recipe

### ISSUE THREAD

**Issue by vkhatri** [svanzoest-cookbooks/apache2#295]
hello!

is it intended to delete `conf.d` directory in `apache2::default`? any explanation is much appreciated. 

    directory "#{node['apache']['dir']}/conf.d" do
      action :delete
      recursive true
    end

**Comment by hrak** [comment]
This issue is still holding us back from rolling out this cookbook in production, as reported by me in #250. In a mixed Ubuntu 12.04 / 14.04 (Apache 2.2/Apache 2.4) environment, rolling out this cookbook will break 12.04 based Apache boxes with config files in conf.d (as is usually the case).

A flag, or as i suggested, a "if node['apache']['version'] == '2.4'" check around the deletion of /etc/apache2/conf.d would be very welcome!

**Comment by svanzoest** [comment]
@hrak are your `conf.d` files not managed by chef? Can you provide the scenario where this is not working for you? How can we migrate the config file creation from `conf.d` to `conf-available`?

The older packages writing configs to conf.d is one such scenario any others?

**Comment by hrak** [comment]
@svanzoest Its mostly that scenario indeed (packages on Ubuntu 12.04 and possibly other distros that drop off config bits in conf.d/, f.e. phpmyadmin). 

Some of our own cookbooks drop small config changes in there as well, but we could simply fix that in our wrapper/app cookbooks by using apache_config.

Migrating from conf.d to conf-available could also be a nice thing to implement. Let the cookbook check for existance of conf.d, if it is there and there are files in there, move them to conf-available and link them in conf-enabled, and then remove the conf.d dir. It would be a nice idempotent solution that does not result in data/config loss.

**Comment by svanzoest** [comment]
@hrak I agree with your comments. My additional concern is that between apache 2.2 and apache 2.4 you can not just copy over the `conf.d` files and enable them as they may not be compatible with apache 2.4 and therefore break a running service in production. It seems tricky to do this on such an upgrade between 2.2 and 2.4.

Of course if we are talking a cookbook only update then it would be a lot easier as it is more likely that the configuration files should continue to work. It seems like the configuration files should be managed by chef though and therefore there would be no config loss at all. The exceptions would be a default configuration dropped by a package that chef is not aware of. Maybe the best way forward to ensure we keep a history of what the configuration files are, is copy them over, but not enable them.

A somewhat related issue is #279 where packages drop in configuration files that are not known by the cookbook, or the cookbook expected those to be deleted, but they would be added again when the new yum package gets installed before the next chef run that can delete them again. I am starting to lean more towards rewriting the config empty, as ugly as that is, to avoid for them to be written again.

**Comment by hrak** [comment]
The cookbook upgrade scenario is the most likely to happen, and the only one I'm worried about atm. I don't think people in for example a mixed Ubuntu 12.04/14.04 environment are crazy enough to combine a major cookbook version bump with a distro upgrade :) (or upgrade a working Apache 2.2 setup to 2.4 and expect things to work flawlessly)

Yum rewriting config files and resetting permissions has bitten me quite some time as well, and i never really found a good way of preventing/fixing it. I guess RPM users just have to trigger a Chef run after running updates ;)

**Comment by dgm** [comment]
As we are only beginning to utilize chef, we have some conf files in conf.d that are not under chef control... and it's a bit of a pain to upgrade servers to this cookbook when I have to first backup the conf.d files, run chef-client, and then restore any missing configs.

**Comment by svanzoest** [comment]
@dgm my suggestion to you is to not do that. Determine what files are in `conf.d` and add them to your chef wrapper cookbook and test them. Once you do that you can just run chef-client and not even worry about it. The configs will be available in `conf-enabled` without a hitch and you now also have documented exactly what is required to configure the web server.
