### ISSUE TITLE
apache_conf uses an undefined service

### ISSUE THREAD

**Issue by shanethehat** [svanzoest-cookbooks/apache2#317]
In the apache_conf definition, the template resource notifies the apache2 service to restart, but this service is not defined. This results in chefspec failures when working with the definition in a simple recipe that does not otherwise include the apache2::default recipe.

**Comment by svanzoest** [comment]
Thanks for using the cookbook. The cookbook was originally written with the assumption that you need to load the `apache2::default` recipe for you to use the definitions. We will need to evaluate this a bit more carefully to determine if we really want the definitions to be used without loading the default recipe first. If we do, we will need to update all the definitions, not just `apache_conf`.

**Comment by shanethehat** [comment]
Hey Sander, thanks for the cookbook! I looked at the other definitions, and most of them do already include the default recipe, so I assumed this was an omission. Looking more carefully, the only other definition that it's missing from is apache_mod, so I will update my PR to include that too.

There is an argument that the user should be including apache::default into any recipe that uses these definitions for their own safety; but I think that by ensuring it is loaded inside the definition, the definition becomes more tolerant. Whether you want to be tolerant or opinionated is up to you!

**Comment by svanzoest** [comment]
Makes sense to me. Thanks!
