### ISSUE TITLE
add flag to set sensitve true in mod definition template

### ISSUE THREAD

**Issue by fsimmend** [svanzoest-cookbooks/apache2#319]
The template defined in the mod definition is spamming the log. A flag to set sensitve = true would prevent that.

**Comment by svanzoest** [comment]
Hi @fsimmend 

I recognize that keeping logs clean is a good thing, but setting a [sensitive attribute](https://docs.chef.io/resource_common.html#attributes) on the template resource does not seem like the right approach. The point behind that is to avoid having passwords and other secrets be exposed. 

Can you provide a sample as to exactly which log lines you are referring to? It would help to ensure we are talking about the same thing.

**Comment by svanzoest** [comment]
Hi @fsimmend can you provide a sample of the log lines you are referring to?
