### ISSUE TITLE
mod_ssl package won't install for apache 2.4 on Amazon Linux 2014.09

### ISSUE THREAD

**Issue by zstate** [svanzoest-cookbooks/apache2#322]
Hi,

It appears that there is a conflict when you try to use apache::mod_ssl recipe with apache 2.4 on Amazon Linux 2014.09. Here is the error:

>Error executing action install on resource 'package[mod_ssl]'
 
>Chef::Exceptions::Exec
returned 1, expected 0
 
>Resource Declaration:
In /var/lib/aws/opsworks/cache.stage2/cookbooks/apache2/recipes/mod_ssl.rb
 
>26:   package 'mod_ssl' do
27:     notifies :run, 'execute[generate-module-list]', :immediately
28:   end
29: 
 
>Compiled Resource:
Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/apache2/recipes/mod_ssl.rb:26:in 'from_file'
 
>package("mod_ssl") do
action :install
retries 0
retry_delay 2
package_name "mod_ssl"
version "2.2.29-1.4.amzn1"
cookbook_name "apache2"
recipe_name "mod_ssl"
end

Looks like for Apache 2.4 it requires mod24_ssl package for Amazon Linux. 
Possibly it can be fixed by specifying package name in the attributes: 
default['apache']['mod_ssl']['package'] = mod24_ssl

package "#{node['apache']['mod_ssl']['package']}" do
    notifies :run, 'execute[generate-module-list]', :immediately
end

Thanks a lot

**Comment by drpebcak** [comment]
@zstate thanks for opening this issue. We do not currently have support for Amazon Linux, but we are trying to work towards this. If you would like to help us work on it, we would love to look at a pull request that implements different package names for different platforms.

**Comment by jorhett** [comment]
I'll send a pull request today or tomorrow, I've already hacked this into a local copy. We need a new attribute for package prefix.

**Comment by drpebcak** [comment]
@jorhett, @zstate I've put some stuff into master that should resolve this. Please let me know if you have a chance to look at it and see if it fixed your problem.

**Comment by drpebcak** [comment]
This is working for me on several systems. I'm calling it good!
