### ISSUE TITLE
mod_proxy_html recipe should install libapache2-mod-proxy-html

### ISSUE THREAD

**Issue by xmik** [svanzoest-cookbooks/apache2#326]
On debian 7.5 , using apache2 2.2.22-13+deb7u3 I used recipe mod_proxy_html but then I still needed to install `libapache2-mod-proxy-html`. Since the recipe mod_php5 installs `libapache2-mod-php5`, the recipe mod_proxy_html should install  `libapache2-mod-proxy-html`. 

After that, when restarting apache2 service I got an error:
````
vagrant@host:~$ sudo service apache2 restart 
apache2: Syntax error on line 106 of /etc/apache2/apache2.conf:  
Syntax error on line 1 of /etc/apache2/mods-enabled/proxy_html.load:  
Cannot load /usr/lib/apache2/modules/mod_proxy_html.so into server:   
/usr/lib/apache2/modules/mod_proxy_html.so: undefined symbol: htmlFreeParserCtxt
Action 'configtest' failed.
The Apache error log may have more information.
failed!
````

The solution for me was to add to /etc/apache2/mods-available/proxy_html.load file this line (as the first line):
````
LoadFile libxml2.so.2
````
It could also be dealt with in mod_proxy_html recipe.

**Comment by svanzoest** [comment]
HI @xmik,

Thank you for using the cookbook and filing your report.
The debian package for [libapache2-mod-proxy-html](https://packages.debian.org/wheezy/libapache2-mod-proxy-html) is no longer used with apache 2.4 (see [jesse](https://packages.debian.org/jessie/libapache2-mod-proxy-html)), so this would be change that is only applicable to apache 2.2.

The requirement to load `libxml2` seems to be an issue that should be filed [upstream]( https://packages.debian.org/wheezy/apache2) if it isn't there already. That is more related to incomplete dependencies for a package.

**Comment by svanzoest** [comment]
@xmik any thoughts on what I said above?

**Comment by svanzoest** [comment]
I added the dependency on `libapache2-mod-proxy-html`, so that should help some folks still on apache 2.2. Thanks for the report.
