### ISSUE TITLE
Pipe of error_log is not possible with current apache2.conf template

### ISSUE THREAD

**Issue by sschueller** [svanzoest-cookbooks/apache2#327]
I can not configure a piped log like so:
<code>
ErrorLog |/usr/local/bin/apache_error.pl
</code>
The current template will append the log path. If I set <code>log_dir</code> to <code>|/usr/local/bin</code>,  <code>apache2/recipes/default.rb</code> will attempt to create that dir which is not possible.

Suggestion is to add a check if <code>error_log</code> starts with a pipe character.

pull request: https://github.com/svanzoest-cookbooks/apache2/pull/328

**Comment by svanzoest** [comment]
Thanks for using and contributing to the cookbook. #328 is merged.
