### ISSUE TITLE
Apache development package attribute

### ISSUE THREAD

**Issue by yoshiwaan** [svanzoest-cookbooks/apache2#330]
Related to https://github.com/svanzoest-cookbooks/apache2/issues/302.

When using Amazon Linux the httpd24 package allows installation of apache 2.4. The associated development package is httpd24-devel (httpd24-devel.x86_64).

The following files have a hard coded reference to the httpd-devel package:
recipes/mod_auth_cas.rb
recipes/mod_auth_openid.rb
recipes/mod_fastcgi.rb
spec/modules/mod_auth_openid_spec.rb
spec/modules/mod_fastcgi_spec.rb

It would be good to be able to override that package name via an attribute as well.

For reference sake there's also httpd24-tools.x86_64 and httpd24-manual.noarch packages.

**Comment by svanzoest** [comment]
Hi,

We currently do not have support for Amazon Linux in this cookbook. We are open to a PR for support. I have added this issue to the Amazon Linux support milestone.

Thanks for your report!

**Comment by yoshiwaan** [comment]
Hi,

The cookbook actually works via attribute overrides on Amazon Linux even if it's not supported natively, it's just the recipes above that reference a hard coded package name that don't work.

Allow that to be set via attribute as well would allow those recipes to work via attribute override in the same was as the rest of the cookbook does.

No big push for full Amazon Linux support needed, just the attribute!

**Comment by drpebcak** [comment]
I've made this work with Amazon Linux and apache2.4. Checkout #322

**Comment by yoshiwaan** [comment]
Neat. Thanks very much.
