### ISSUE TITLE
SSLStrictSNIVHostCheck breaks apache in RHEL 5

### ISSUE THREAD

**Issue by scottymarshall** [svanzoest-cookbooks/apache2#331]
SSLStrictSNIVHostCheck did not come out until apache 2.2.12, which is further than what you can upgrade to in RHEL 5: http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslstrictsnivhostcheck

**Comment by scottymarshall** [comment]
https://github.com/svanzoest-cookbooks/apache2/pull/332

**Comment by svanzoest** [comment]
Hi @scottymarshall,

Thanks for the issue. Keep in mind that we do not actively work to maintain backwards compatibility with RHEL5 as it is in in the [RHEL Production 3 Phase](https://access.redhat.com/support/policy/updates/errata#Production_3_Phase).

It looks like the latest openssl available is [0.9.8e-32.el5_11](https://rhn.redhat.com/errata/RHBA-2015-0026.html) and the latest apache httpd is [2.2.3-91.el5](https://rhn.redhat.com/errata/RHBA-2014-1232.html).

This means that no new feature development has been done in many years and also several openssl and apache 2.2.x bugfix releases are not available.

I am okay with seeing what we can do to keep it working on that platform, but realize that we are spending all our efforts on RHEL7 which will support features such as strict SNI checking on vhosts. Our goal is to maintain the two major long term (stable) releases from each supported vendor.

**Comment by scottymarshall** [comment]
I agree.  RHEL5 is on its way out and we should be focused on RHEL7, but unfortunately I have not been able to convince my IT shop of this, so I am stuck with it for a while.

Take a look at the pull request and you will see that it does not harm later versions of apache to merge the change.  I only remove SSLStrictSNIVHostCheck from the config when it is set to "Off".  Since the default is Off, not having it in the file is not a big deal.

And not having it in the file also makes it backwards compatible.

**Comment by svanzoest** [comment]
Merged #332
