### ISSUE TITLE
Incorrectly claims that the cookbook has no dependencies

### ISSUE THREAD

**Issue by kinghrothgar** [svanzoest-cookbooks/apache2#334]
The README claims "This cookbook doesn't have direct dependencies on other cookbooks, as none are needed for the default recipe or the general use cases."  However both iptables and logrotate are in the metadata as depends.  This means the cookbook can't be compiled without these.  Because of this I believe they should be listed as dependencies in the README as the cookbook is unusable without them...

**Comment by drpebcak** [comment]
This is actually an interesting point. Do we want to remove those dependencies from the metadata? We don't use actually include logrotate or iptables by default. We've got wrapper recipes if people decide to use them, but they aren't required for a 'default' setup.

**Comment by kinghrothgar** [comment]
I would be really nice if we could remove them.  I actually switched to using the logrotate cookbook to making using this easier (and because I liked it) but switching to the community iptables cookbook is impossible for my setup.  To use this I had to fork it and remove the depends.

**Comment by drpebcak** [comment]
@svanzoest any objections to removing those dependencies?

**Comment by svanzoest** [comment]
Originally we did not have the dependencies listed, however, that means we could not test those recipes. We need to either remove those recipes entirely or update the README to confirm the dependencies.

Having a dependency on the community cookbook is not a huge big deal as long as we do not rely on particular versions as we could get caught behind a version constraint stopping usage of the cookbook.

So, yes, I object to removing the dependency by itself. If we want to make a call saying we would also remove the funcionality, I am open to discussing that. The easiest thing to do for now would be to update the README to reflect the current state of the cookbook.

**Comment by drpebcak** [comment]
I've updated the README, but I don't want to close this issue until we decide which way to go with it.

**Comment by drpebcak** [comment]
@svanzoest I wonder if we would be better suited to let people handle firewalls/log rotation in their own wrapper cookbooks. That way they could have maximum flexibility, and we wouldn't have to worry about the dependencies just for those two recipes.

**Comment by svanzoest** [comment]
@drpebcak Let's remove `apache2::iptables`, `apache2::god_monitor`, `apache2::logrotate` and let people handle that in their wrapper cookbooks and remove the dependencies. We will want to update the change log to reflect that.
