### ISSUE TITLE
Wrong apache version installed on Amazon Linux

### ISSUE THREAD

**Issue by ikben** [svanzoest-cookbooks/apache2#343]
I'm running Amazon Linux 2014.9

On [line 60 in attributes/default.rb](https://github.com/svanzoest-cookbooks/apache2/blob/master/attributes/default.rb#L60) `default['apache']['version']` get's set to `2.4` but [on line 86 in the same file](https://github.com/svanzoest-cookbooks/apache2/blob/master/attributes/default.rb#L86) `default['apache']['package']` is set to `httpd`.

This should be `httpd24` if you want to use Apache2.4 on Amazon Linux. `httpd` installs Apache2.2

**Comment by drpebcak** [comment]
Nice catch, thanks!

**Comment by svanzoest** [comment]
Looks good, but it seems like it broke the build.

**Comment by drpebcak** [comment]
This should be fixed when the tests for this build - 970ca5c - finish running.
