### ISSUE TITLE
Unable to install apache with php on 14.04

### ISSUE THREAD

**Issue by SinisterLight** [svanzoest-cookbooks/apache2#346]
Trying to install apache2 with php, unable to start 

Ubuntu 14.04
 
 recipes installed

default
mod_python
mod_php5
mod_cgi
mod_ssl
mod_rewrite

Starting web server apache2                                                                                                                                         The apache2 configtest failed.
Output of config test was:
[Fri Apr 17 11:51:29.430754 2015] [:crit] [pid 5040:tid 140224518735744] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
AH00013: Pre-configuration failed
Action 'configtest' failed.
The Apache error log may have more information.

**Comment by SinisterLight** [comment]
after doing

 override['apache']['mpm'] = 'prefork'

It works.

looking at the attribute file, default is 'event'
But this say it should be prefork
https://wiki.archlinux.org/index.php/Apache_HTTP_Server#PHP

Should default value be changed ?

**Comment by martinb3** [comment]
I believe on 14.04, the default is event, when installed from their packages, ArchLinux's wiki non-withstanding.

**Comment by drpebcak** [comment]
Are you using ubuntu or arch?

**Comment by svanzoest** [comment]
As @martinb3 states, the default mpm used in the cookbook should match that of the default on that operating system. You can override this by specifying it by setting `apache.mpm` before the cookbook runs. We definitely want to make MPM switching better, but it is currently not very well supported on most platforms. The enhancement is tracked as #236.

I will close this it looks like your question was answered.
