### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by PierreRambaud** [svanzoest-cookbooks/apache2#347]
Hi,
Current version on the supermarket not working with Ubuntu 14.4 and Debian wheezy due to incompatibly with 2.4, can you please release a new version?

Regards

**Comment by drpebcak** [comment]
What issue are you seeing? This cookbook does support Apache2.4.

**Comment by PierreRambaud** [comment]
This one when using supermarket package.
```
           ================================================================================
           Error executing action `run` on resource 'execute[a2enmod authz_default]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /usr/sbin/a2enmod authz_default ----
           STDOUT: 
           STDERR: ERROR: Module authz_default does not exist!
           ---- End output of /usr/sbin/a2enmod authz_default ----
           Ran /usr/sbin/a2enmod authz_default returned 1
```

No problem when using a Berksfile pointing on this repository.

**Comment by drpebcak** [comment]
What's in your run list?

**Comment by drpebcak** [comment]
Here is the recipe for mod_authz_default as of 3.0.1 - https://github.com/svanzoest-cookbooks/apache2/blob/v3.0.1/recipes/mod_authz_default.rb

It just includes mod_authz_core. How are you getting to the stage where the cookbook is trying to execute `a2enmod authz_default`?

**Comment by svanzoest** [comment]
Do you have `node['apache']['default_modules']` set on the node? The cookbook [sets the default](https://github.com/svanzoest-cookbooks/apache2/blob/v3.0.1/attributes/default.rb#L306-L309), but maybe you have overwritten it?

**Comment by PierreRambaud** [comment]
Sorry, seems to be my fault, after looking an other cookbook have failed
dependency to this cookbook :/
