### ISSUE TITLE
Amazon Linux + mod_php5 recipe

### ISSUE THREAD

**Issue by yoshiwaan** [svanzoest-cookbooks/apache2#348]
Hi,
Amazon linux supports installing different version of PHP via package. This creates different versions of the .so apache module in /usr/lib64/httpd/modules.

Amazon linux then uses a couple of symlinks to set a default php version as it were, which is probably easier to just see than describe:

    [ec2-user@php55 ~]$ ls -l /usr/lib64/httpd/modules/libphp*
    -rwxr-xr-x 1 root root 4253400 Apr 17 18:08 /usr/lib64/httpd/modules/libphp-5.5.so
    lrwxrwxrwx 1 root root      27 Apr 20 20:55 /usr/lib64/httpd/modules/libphp.so -> /etc/alternatives/libphp.so
    -rwxr-xr-x 1 root root 4470216 Apr 17 18:08 /usr/lib64/httpd/modules/libphp-zts-5.5.so
    lrwxrwxrwx 1 root root      31 Apr 20 20:55 /usr/lib64/httpd/modules/libphp-zts.so -> /etc/alternatives/libphp-zts.so
    [ec2-user@php55 ~]$ ls -l /etc/alternatives/libphp*
    lrwxrwxrwx 1 root root 38 Apr 20 20:55 /etc/alternatives/libphp.so -> /usr/lib64/httpd/modules/libphp-5.5.so
    lrwxrwxrwx 1 root root 42 Apr 20 20:55 /etc/alternatives/libphp-zts.so -> /usr/lib64/httpd/modules/libphp-zts-5.5.so

The long and the short of it is that Amazon linux had to be different and decided to make the module file link as libphp.so instead of libphp5.so, which is hard coded in the mod_php5 recipe, so that recipe doesn't work in this cookbook.
Now I've only tested this on php5.5, so I'm guessing php5.6 does the same but I'm not sure about php5.4 or php5.3. I wouldn't be surprised if php5.3 acted like the default php package in other EL distros...

While I'm at it, is there an ETA for the next release of this cookbook? All the extra code added to allow Amazon Linux to work easily would be nice to have right now but I don't want to use the master branch of github as a source.

**Comment by svanzoest** [comment]
I think the biggest thing holding back a release right now is a full regression test-kitchen run on all supported platforms and making sure it comes back clean. Once that is completed we can do a release.

The issues with dealing with different versions on all platforms really make the tests and scenarios spiral out of control. So, we generally focus on a main configuration per platform (usually the default) that we support and attempt to allow someone to use any other configurations that are possible, but you'd be on your own.

Thanks for the additional feedback on Amazon Linux. I added it to the milestone, so we can keep this in mind.

**Comment by yoshiwaan** [comment]
Thanks Sander.

I think it's perfectly reasonable to only support a default configuration and the way the rest of the cookbook supports alteration via attribute overrides is the best way to do it.

So if that php module filename could be an attribute as well then it's probably the easiest and most consistent way to fix it.

But I think you already knew that ;)

**Comment by svanzoest** [comment]
We should combine the effort of this with #339, as I think it is essentially the same issue?
