### ISSUE TITLE
Duplicate section of apache2.conf.erb

### ISSUE THREAD

**Issue by yoshiwaan** [svanzoest-cookbooks/apache2#349]
I know it's not released yet but I thought I'd raise an issue in case no one noticed before it went to a release.

In the master branch search for "# Sets the default security model" in templates/default/apache2.conf.erb

There is a section of configuration that is probably a work in progress but is currently a duplicate of an existing section.  I doubt it breaks anything but it's messy.

**Comment by drpebcak** [comment]
Thanks!

I removed the duplicate section.
