### ISSUE TITLE
Apache always failed when restarting the first time

### ISSUE THREAD

**Issue by PierreRambaud** [svanzoest-cookbooks/apache2#356]
Hi,
After a simple `include_recipe 'apache2'` on an Ubuntu 14.04 (apache 2.4.7) with this box (using chef-provisioning)

```
vagrant_box 'ubuntu14' do
  url 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box'
end
```

I catched this error:

```
root@foreman:~# apache2 -t
[Thu May 28 06:41:53.017929 2015] [core:warn] [pid 17814:tid 139689850587008] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
(2)No such file or directory: AH02297: Cannot access directory '/etc/apache2/${APACHE_LOG_DIR}/' for log file '${APACHE_LOG_DIR}/other_vhosts_access.log' defined at /etc/apache2/conf-enabled/other-vhosts-access-log.conf:2
AH00014: Configuration check failed
```

Did I do something wrong?

Regards,

**Comment by svanzoest** [comment]
This is related to needing to load the etc/defaults first. I would
recommend you use apachectl configtest instead.

**Comment by PierreRambaud** [comment]
In fact, I just executed this command because `service[apache2]` are running it in `only_if` resource parameter.

**Comment by svanzoest** [comment]
If that guard kicks in the config has syntax errors. What does `apache2ctl configtest` return as the reason for the syntax error?

**Comment by PierreRambaud** [comment]
HI and sorry for the delay,

This is what both commands are returning:
```
root@front1:~# apache2ctl configtest
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Syntax OK

root@front1:~# apache2 -t
[Mon Jun 15 10:24:08.978366 2015] [core:warn] [pid 9321] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
(2)No such file or directory: AH02297: Cannot access directory '/etc/apache2/${APACHE_LOG_DIR}/' for log file '${APACHE_LOG_DIR}/other_vhosts_access.log' defined at /etc/apache2/conf-enabled/other-vhosts-access-log.conf:2
AH00014: Configuration check failed
```

I think you must change the `only_if` block at this line: https://github.com/svanzoest-cookbooks/apache2/blob/5f10550ff89c20306f4160025425315141bdefed/recipes/default.rb#L219

Regards

**Comment by svanzoest** [comment]
It looks like the error that caused the `only_if` to fail has been resolved, so the block will succeed. Until we figure out what caused it to fail, there is not much I can do.

**Comment by PierreRambaud** [comment]
Seems to be fixed with latest commits
