### ISSUE TITLE
Can't Enable/Disable Sendfile

### ISSUE THREAD

**Issue by HeathNaylor** [svanzoest-cookbooks/apache2#359]
There is an issue with Sendfile and Virtualbox (https://www.virtualbox.org/ticket/9069). When using this cookbook with Vagrant and Virtualbox as the provider this bug is encountered. I want to be able to toggle `EnableSendfile On` or `EnableSendfile Off` within `apache2.conf.erb` using something like `@params`. I have given it a try on my end but it seems that `@params` is not accessible from withing `apache2.conf.erb`. This is a pretty major blocker for us, we are having to manually change the `apache2.conf` file after `vagrant up`.

**Comment by svanzoest** [comment]
You can write arbitrary config snippets by using the `apache_conf` definition. 

For example: write a template in `templates/default/` of your wrapper coobkook such as `my_apache2/templates/default/sendfile.conf.erb` containing `EnableSendfile Off` and reference it in your wrapper cookbook as follows:

```ruby
include_recipe "apache2"

apache_conf "sendfile" do
  source "sendfile.conf.erb"
  cookbook "my_apache2"
  enable true
end
```
This will add it to your config file via the `conf-enabled` directory.

**Comment by HeathNaylor** [comment]
@svanzoest and then would my `sendfile.conf.erb` just be `EnableSendFile Off`?

**Comment by svanzoest** [comment]
Yes. You can set as many directives that way as you want with as many
templates as you want.

**Comment by HeathNaylor** [comment]
This fixed my issue, thank you.
