### ISSUE TITLE
.htaccess/.htpasswd regex should be escaped

### ISSUE THREAD

**Issue by cmann** [svanzoest-cookbooks/apache2#362]
In `templates/default/apache2.conf.erb` there's a `File` directive to disallow access to .htaccess/.htpassword files. The `.` character needs to be escaped on lines 96 and 98 as it's currently treated as a wildcard.

Eg. I use the cookbook to help deploy a mirror of the Ubuntu archives and the `shtool` package cannot be downloaded without manually modifying the configuration as it matches the existing expression.

Fix is in pull request #363 

It also looks like the use of `node['apache']['access_file_name']` as both a string (for AccessFileName) and a regex (in file_name_prefix) could cause similar bugs, if I'm not mistaken. If any of the first three characters of the attribute have special meaning in a regex they'd need to be escaped first.

**Comment by svanzoest** [comment]
:+1: thanks. I will merge shortly.
