### ISSUE TITLE
apache installation does not work if 'default['apache']['dir']' or 'default['apache']['conf_dir']' are set outside /etc directory

### ISSUE THREAD

**Issue by joshoohaah** [svanzoest-cookbooks/apache2#366]
There are multiple errors when you configure either 'default['apache']['dir']' or 'default['apache']['conf_dir'] to use custom locations.

Example
`default['apache']['dir'] = '/apps/httpd'`
`default['apache']['docroot_dir'] = '/data/httpd/htdocs'`
`default['apache']['conf_dir'] = '/data/httpd/conf'`

get errors that certain directories aren't created
`AH00112: Warning: DocumentRoot [/data/httpd/htdocs/] does not exist`

error when 'default['apache']['conf_dir']' is outside of /etc:
`httpd: Syntax error on line 221 of /etc/httpd/conf/httpd.conf: Include directory '/etc/httpd/conf.d' not found`
Problem seems to be a generic httpd.conf gets created then with the absence of it in that default location..and it points to incorrect files.

**Comment by joshoohaah** [comment]
And if you put 'default['apache']['dir']' to use a different folder....oh man.  then things get really wonky.  then files get deployed to the custom location defined.  but then also there still is an installation in '/etc/httpd'.

(FYI, this the behavior seen in centos/rhel/oracle).

**Comment by svanzoest** [comment]
Hi,

Are you also updating the location in the apache2 binary to match? The
cookbook has no control over the package that is installed and attempts to
match the package defaults within the cookbook. If you change those without
changing the package it simply will crash and burn. Don't do that :-)

**Comment by svanzoest** [comment]
You can change the doc_root but you will need to make sure the directory
exists. I highly recommend you do not change conf_dir or dir unless you are
ready to deal with the fallout.

What are you trying to accomplish that makes you want to change the default
locations?

**Comment by joshoohaah** [comment]
thanks for the quick response svanzoest.   The reason the request for changes is I'm going to make ebs mount points for locations such /logs, /apps/...etc.  

Upon initial viewing of your cookbook, the parameterized attributes led me to believe i could specify the folder locations (when in reality currently the way the cookbook is setup you should NEVER edit the 'dir' directory). 

I think a solution to this is to compare the default `['apache']['dir']` locations (which you set in the attributes file), and what the user has set in `['apache']['dir']`.  If those locations differ...delete the location in /etc/httpd..and make a symbolic link from the user specified `['apache']['dir']` to what the application is expecting.

Its possible a new attribute might need to be created for this...or maybe not.

**Comment by svanzoest** [comment]
@joshoohaah the `apache.dir` attribute matches what is hardcoded in the apache binary as `HTTPD_ROOT`, this needs to be changed at compile time and is not something that can be changed via configuration of the package.

There are a lot of changes you can make by adjusting the parameters and by using templates dropped in `conf-enabled` or `sites-enabled`, but I would refrain from making any changes outside of those.

Are you planning to use the same instance of apache for each `/apps/` app?

**Comment by joshoohaah** [comment]
I found this issue by adjusting the parameters.  I do not think you should have the `['apache']['dir']` as a parameterized attribute if you should never change it (except in the case if you change the binary, as you alluded to).
Right now if you want a different directory for `dir` or `conf_dir`, essentially you would have to:
   1. create binaries with new locations
   1. create yum repo or some other mode to deploy package
   1. modify `dir` and `conf` attributes in wrapper cookbook to point to this location

what i suggest (at least for `conf_dir`) is to compare the passed in `conf_dir` with the platform default (as specified currently in attributes file).  if they don't match..run something like this

```
#deletes httpd.conf in incorrect location
directory "/etc/httpd/conf" do
  recursive true
  action :delete
end

%W(
#{node['apache']['conf_dir']}
).each do |dir|
  directory dir do
    mode '0755'
    owner 'root'
    group node['apache']['root_group']
    recursive true
  end
end


link "/etc/httpd/conf" do
  to "#{node['apache']['conf_dir']}"
end
```

**Comment by joshoohaah** [comment]
![screen shot 2015-06-29 at 2 53 57 pm](https://cloud.githubusercontent.com/assets/8366405/8416932/b98fac50-1e6e-11e5-85e1-c36ee03a6d94.png)

I tested this code in this fashion and it will work with this logic.   I think some logic needs to be put around it comparing the directory in the attributes with the default though

**Comment by drpebcak** [comment]
@joshoohaah the attributes are also changeable in the case that you are on a platform that we currently do not set things right on.

I don't think it is likely that we will support symlinking the config directories to elsewhere in the filesystem.

**Comment by joshoohaah** [comment]
drpebcak, thanks for the response.  If thats the direction/choice for the cookbook thats fine.  It just wasn't obvious upon first glance.
It seems though it would make the cookbook more robust to take in these accounts.  Either way, just trying to help! :)
