### ISSUE TITLE
Support for setting apache umask

### ISSUE THREAD

**Issue by Jamstah** [svanzoest-cookbooks/apache2#370]
Setting the umask of an apache server is a fairly common thing to do, and is often done by updating /etc/sysconfig/httpd (RHEL) or /etc/apache2/envvars (debian) with a line to set the umask.

As these files are controlled by this cookbook, it would be nice to have the option of setting a umask in the recipes.

**Comment by svanzoest** [comment]
This is already supported by adding any additional parameter you want to the `apache.sysconfig_additional_params` hash and will add it. I do think that adding an example how to that with umask is probably a good thing to have in the README.

Let us know if that works for you.
