### ISSUE TITLE
Recipe mod_ssl assumes a mod_ssl package needs to be installed on suse platforms

### ISSUE THREAD

**Issue by kleini** [svanzoest-cookbooks/apache2#385]
At least for SUSE Linux Enterprise 12 this is not the case.

       Recipe: apache2::mod_ssl
       
           
           ================================================================================
           Error executing action `install` on resource 'zypper_package[mod_ssl]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '104'
           ---- Begin output of zypper --non-interactive install --auto-agree-with-licenses mod_ssl ----
           STDOUT: Loading repository data...
           Reading installed packages...
           'mod_ssl' not found in package names. Trying capabilities.
           STDERR: No provider of 'mod_ssl' found.
           ---- End output of zypper --non-interactive install --auto-agree-with-licenses mod_ssl ----
           Ran zypper --non-interactive install --auto-agree-with-licenses mod_ssl returned 104
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/apache2/recipes/mod_ssl.rb
           
            26:   package node['apache']['mod_ssl']['pkg_name'] do
            27:     notifies :run, 'execute[generate-module-list]', :immediately
            28:   end
            29: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/apache2/recipes/mod_ssl.rb:26:in `from_file'
           
           zypper_package("mod_ssl") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "mod_ssl"
             declared_type :package
             cookbook_name :apache2
             recipe_name "mod_ssl"
           end

Here is the list of available packages regarding apache and ssl.

    singlenode:~ # zypper search apache
    Loading repository data...
    Reading installed packages...

    S | Name                               | Summary                                                                 | Type      
    --+------------------------------------+-------------------------------------------------------------------------+-----------
      | apache-commons-beanutils           | Utility methods for accessing and modifying the properties of JavaBeans | package   
      | apache-commons-beanutils-javadoc   | Javadoc for jakarta-commons-beanutils                                   | package   
      | apache-commons-codec               | Apache Commons Codec Package                                            | package   
      | apache-commons-collections         | Commons Collections Package                                             | package   
      | apache-commons-collections-javadoc | Javadoc for apache-commons-collections                                  | package   
      | apache-commons-daemon              | Commons Daemon - Controlling of Java Daemons                            | package   
      | apache-commons-daemon-javadoc      | Commons Daemon Javadoc                                                  | package   
      | apache-commons-httpclient          | Feature rich package for accessing resources via HTTP                   | package   
      | apache-commons-io                  | Utilities to assist with developing IO functionality                    | package   
      | apache-commons-logging             | Apache Commons Logging                                                  | package   
    i | apache2                            | The Apache Web Server Version 2                                         | package   
      | apache2                            | The Apache Web Server Version 2                                         | srcpackage
      | apache2-doc                        | Additional Package Documentation                                        | package   
      | apache2-example-pages              | Example Pages for the Apache 2 Web Server                               | package   
      | apache2-mod_apparmor               | AppArmor module for apache2                                             | package   
      | apache2-mod_auth_kerb              | Kerberos Module for Apache                                              | package   
      | apache2-mod_jk                     | Connectors between Apache and Tomcat Servlet Container                  | package   
      | apache2-mod_nss                    | SSL/TLS module for the Apache HTTP server                               | package   
      | apache2-mod_perl                   | Embedded Perl for Apache                                                | package   
      | apache2-mod_python                 | A Python Module for the Apache 2 Web Server                             | package   
      | apache2-mod_security2              | ModSecurity Open Source Web Application Firewall                        | package   
    i | apache2-prefork                    | Apache 2 "prefork" MPM (Multi-Processing Module)                        | package   
    i | apache2-utils                      | Apache 2 utilities                                                      | package   
    i | apache2-worker                     | Apache 2 worker MPM (Multi-Processing Module)                           | package   
    singlenode:~ # zypper search ssl   
    Loading repository data...
    Reading installed packages...

    S | Name                       | Summary                                                                      | Type      
    --+----------------------------+------------------------------------------------------------------------------+-----------
      | libgnutls-openssl27        | The GNU Transport Layer Security Library                                     | package   
    i | libopenssl1_0_0            | Secure Sockets and Transport Layer Security                                  | package   
      | libopenssl1_0_0-32bit      | Secure Sockets and Transport Layer Security                                  | package   
      | libopenssl1_0_0-hmac       | HMAC files for FIPS-140-2 integrity checking of the openssl shared libraries | package   
      | libopenssl1_0_0-hmac-32bit | HMAC files for FIPS-140-2 integrity checking of the openssl shared libraries | package   
    i | openssl                    | Secure Sockets and Transport Layer Security                                  | package   
      | openssl                    | Secure Sockets and Transport Layer Security                                  | srcpackage
      | openssl-doc                | Additional Package Documentation                                             | package   
      | openssl-ibmpkcs11          | OpenSSL Dynamic PKCS #11 Engine                                              | package   
      | openssl_tpm_engine         | OpenSSL TPM interface engine plugin                                          | package   
      | perl-Crypt-OpenSSL-RSA     | RSA encoding and decoding, using the openSSL libraries                       | package   
      | perl-Crypt-OpenSSL-Random  | Crypt::OpenSSL::Random Perl module                                           | package   
      | perl-Crypt-SSLeay          | OpenSSL support for LWP                                                      | package   
      | perl-IO-Socket-SSL         | Nearly transparent SSL encapsulation for IO::Socket::INET.                   | package   
      | perl-Net-SSLeay            | Perl extension for using OpenSSL                                             | package   
      | python-pyOpenSSL           | Python wrapper module around the OpenSSL library                             | package   

The Apache module mod_ssl seems to be installed with the binary apache package

    singlenode:~ # ls -lh /usr/lib64/apache2-worker/mod_ssl.so 
    lrwxrwxrwx 1 root root 21 Sep 16 10:21 /usr/lib64/apache2-worker/mod_ssl.so -> ../apache2/mod_ssl.so
   singlenode:~ # ls -lh /usr/lib64/apache2/mod_ssl.so 
   -rwxr-xr-x 1 root root 207K Apr 10 15:08 /usr/lib64/apache2/mod_ssl.so

I tried workaround like setting default['apache']['mod_ssl']['pkg_name'] to an empty string or nil but this all makes the zypper_package resource fail.

When do you expect to fix this hardcoded problem? Is there any other workaround?

**Comment by svanzoest** [comment]
We have worked on OpenSUSE 13, but we do not have access to SLES12, so although we would like it work for SLES 12 it is not part of our test kitchen configuration.

**Comment by kleini** [comment]
I just need something to disable this package installation. Will create a pull request with a fix for my case.

**Comment by drpebcak** [comment]
I'm not sure if we want to disable this for all cases where platform = suse... Does this same issue effect everyone using SLES? Or is it only SLES 12/this particular package source?

Is mod_ssl in the default run_list? I'd say a workaround would be to not use the mod_ssl recipe - just drop the config files in your wrapper recipe instead.

**Comment by kleini** [comment]
I will test SLES 11, too. Currently I don't know about any other SUSE Linux Enterprise platform.
mod_ssl is not in the default run_list. Not using mod_ssl recipe is not a workaround. Especially when using Enterprise Linux platforms I want to configure Apache with SSL, because I am setting up enterprise software that needs encrypted web interfaces.

**Comment by drpebcak** [comment]
I think it's a perfectly valid workaround until we solve the problem. All the recipe really does is install mod_ssl and drop config files. If you already have mod_ssl installed, you can write a quick wrapper that drops the config files from the apache2 cookbook and use that instead of the official mod_ssl recipe. Not saying that's a permanent solution, but it fixes your problem for now so we can work in this.

**Comment by kleini** [comment]
I was able to work around this by doing the stuff from the mod_ssl recipe in my wrapper cookbook when I discover a SUSE Linux Enterprise distribution.

**Comment by svanzoest** [comment]
Closing this in favor of #386
