### ISSUE TITLE
Support alternative Apache module names/versions (use proper module name per platform)

### ISSUE THREAD

**Issue by jkulak** [svanzoest-cookbooks/apache2#391]
I want to install `apache2::mod_pagespeed` for Apache 2.4 on Ubuntu 14.04.

It's same package_link for both Apache 2.4 and earlier versions, but for Apache 2.4 one should load `mod_pagespeed_ap24.so` instead of `mod_pagespeed.so` (as described here: https://developers.google.com/speed/pagespeed/module/install).

Currently it's not supported out of the box. 

I'm using my wrapper cookbook, with custom mod_pagespeed.rb recipe to make that work.

**Comment by drpebcak** [comment]
@jkulak please report issues with mod_pagespeed over in the mod_pagespeed_cookbook repository. https://github.com/drpebcak/mod_pagespeed_cookbook
