### ISSUE TITLE
Template web_app fails when you provide no server_port param

### ISSUE THREAD

**Issue by 8la** [svanzoest-cookbooks/apache2#392]
Think this should fix: https://docs.chef.io/libraries.html#template-helper-modules

Here is the output:

```ruby
Chef::Mixin::Template::TemplateError (uninitialized constant Erubis::RubyEvaluator::Apache2) on line #1:
       
         1: <VirtualHost *:<%= @params[:server_port] || Apache2::Listen.listen_ports_by_address(node).values.map(&:to_a).flatten.first %>>
```

**Comment by 8la** [comment]
Using cloned version from github it  works.

With supermarket version, it breaks!

**Comment by drpebcak** [comment]
The version on the supermarket doesn't have the new listen stuff - it looks like this
`<VirtualHost *:<%= @params[:server_port] || node['apache']['listen_ports'].first %>>`

**Comment by 8la** [comment]
Sorry 4 the noise! :)
