### ISSUE TITLE
Cant install cookbook via supermarket

### ISSUE THREAD

**Issue by karnold** [svanzoest-cookbooks/apache2#396]
When trying to install this cookbook it fails with **"ERROR: Chef::Exceptions::MetadataNotFound: No metadata.rb or metadata.json found for cookbook apache2 in /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks"**

Manually downloading the cookbook and extract it and it does not complain however. 

```
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

And the full output from my terminal
```
it101:chef-repo karnold$ knife cookbook site install apache2
Installing apache2 to /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-apache2) exists, switching to it.
Downloading apache2 from Supermarket at version 3.1.0 to /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks/apache2.tar.gz
Cookbook saved: /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks/apache2.tar.gz
Removing pre-existing version.
Uncompressing apache2 version 3.1.0.
Removing downloaded tarball
No changes made to apache2
Checking out the master branch.
ERROR: Chef::Exceptions::MetadataNotFound: No metadata.rb or metadata.json found for cookbook apache2 in /Users/karnold/src/SFMOMA-DevOps/chef-repo/cookbooks

```

**Comment by drpebcak** [comment]
This seems like more a question for Chef/Supermarket. We do include a metadata with the cookbook (as you can see when you download the tarball with `knife cookbook site download apache2`

**Comment by karnold** [comment]
Im curious as to why it only happens with this package.  The issue hasnt surfaced for any other cookbooks ive tried to install via this method

**Comment by drpebcak** [comment]
I can't say, other than I can tell you that we don't do anything special when we upload to the supermarket.

You could try adding `-VV` to the command to see if you get more information.

**Comment by karnold** [comment]
From what I can tell so far this seems to be an issue revolving around repositories that provide a metadata.json instead of the metadata.rb that is prefered by chef.  Still searching for empirical evidence.
