### ISSUE TITLE
restart apache when mod_proxy module enabled

### ISSUE THREAD

**Issue by patcon** [svanzoest-cookbooks/apache2#398]
EDIT: Seems that there's a flag on `apache_module` resource to restart apache rather than simply reload when adding a new module, and that resolves the issue. I can add support for doing then specifically on ubuntu 12.04

----------------------------------------------
*Original issue text:*

Seems I'm hitting this issue with mod_proxy on Ubuntu 12.04:

* https://serverfault.com/questions/454421/apache-httpd-error-proxy-ap-get-scoreboard-lb-with-proxypass
* http://apache-http-server.18135.x6.nabble.com/Error-proxy-ap-get-scoreboard-lb-90-failed-in-child-td4746072.html

Any thoughts on how best to get around this? Can we add a `[:stop, :start]` notification *on* the apache_module definition, or is this something we'd need to amend *inside* the definition itself?

Or am I stuck working around it manually on ubuntu 12.04. It was quite a confusing thing to sort out, so I'd love to save the next person the trouble :)

**Comment by patcon** [comment]
Submitted PR here: https://github.com/svanzoest-cookbooks/apache2/pull/399

**Comment by svanzoest** [comment]
Closing in favor of #399
