### ISSUE TITLE
Unable to disable mod_deflate to mitigate BREACH

### ISSUE THREAD

**Issue by phrag** [svanzoest-cookbooks/apache2#404]
Using deflate or gzip compression on a page with secrets allows for the BREACH attack: http://breachattack.com/

This is 2 years old now, but still a real threat.

I see no way to disable mod_deflate by an attribute.

From apache2 cookbook docs:
"in your cookbook, after include_recipe 'apache2' use the apache_module definition to enable/disable the required module"
```
apache_module "mod_deflate" do
      enable false
    end
```

Using rewind does not work as the cookbook enables mod_deflate by default and cannot be disabled with an attribute.

Please expose this configuration as an attribute, thank you! =)

**Comment by svanzoest** [comment]
We can make that adjustable, however, I think compression is generally a
positive.

You can turn it off explicitly where you deal with secrets via directives
in your apache config. See
https://qualys.jive-mobile.com/#jive-discussion?content=%2Fapi%2Fcore%2Fv2%2Fdiscussions%2F12052
for some examples. I would caution using referer though as that can easily
be fabricated in a crafted request.

**Comment by phrag** [comment]
Thank you @svanzoest, i will try this and get back to you

**Comment by phrag** [comment]
I am unable to figure out how best to make this module configurable, the modules are enabled in a loop from what i understand. Can you suggest the best way to achieve this please? 
There are several security issues related to HTTP compression which i am trying to mitigate but am struggling to implement with chef.

**Comment by drpebcak** [comment]
@phrag he is suggesting that you leave the module enabled globally, but turn it off in your vhosts where relevant - as in the example link he posted.

**Comment by svanzoest** [comment]
If you do not think the above solution is enough, you can update `apache.default_modules` based on the changes for #401 which will be in the next release.
