### ISSUE TITLE
Automatically starting apache on include_recipe "apache2"

### ISSUE THREAD

**Issue by t0m** [svanzoest-cookbooks/apache2#405]
Hi, I'm having some issues with how the cookbook tries to start apache whenever the default recipe is included. At the very bottom of default.rb:

```
service 'apache2' do
  ........
  service_name apache_service_name
  action [:enable, :start]
  only_if "#{node['apache']['binary']} -t", :environment => { 'APACHE_LOG_DIR' => node['apache']['log_dir'] }, :timeout => 10
end
```

 In both development and production it would be nice to have more control over when httpd is started, since there's some cases the server may be in an incomplete state, we may not be ready to serve traffic yet, or we may just want to install apache and have something else start it later. Perhaps there could be an option to change an immediate start to a delayed one, so other recipes have a chance to run?

**Comment by svanzoest** [comment]
One of the challenges here is that we are not fully in control here as most package based apache installations will already start the service and this mostly checks that it has a valid config and confirms the state in chef. 

I am open to entertain any PRs that would enhance this experience.
