### ISSUE TITLE
Loglevel should be set via node attribute.

### ISSUE THREAD

**Issue by adamhamner** [svanzoest-cookbooks/apache2#406]
It would be nice if Loglevel was controlled via node attribute. 

https://github.com/svanzoest-cookbooks/apache2/blob/master/templates/default/apache2.conf.erb#L150

an attribute like

node.default[:apache][:log_level] = 'warn'

which could be overridden within a role or recipe.

**Comment by svanzoest** [comment]
You can drop a conf template in cond.d and override that with what ever you
want in a wrapper cookbook.
