### ISSUE TITLE
Libraries are not available on ubuntu site anymore

### ISSUE THREAD

**Issue by rohitgabriel** [svanzoest-cookbooks/apache2#412]
Hi,

I tried to use this cookbook and I am new to chef. I could not understand how the list is made for the libraries based on ubuntu version and download the same from https://us.archive.ubuntu site. I get 404's while the cookbook is being executed on the VM. The libraries it is trying to download no longer exist on the ubuntu site which has newer versions. I tried to install apt cookbook before the apache2 cookbook is run but it does not help. I am using version 14.10 ubuntu. Need some help. Thanks.

==> default:     
==> default: Err http://us.archive.ubuntu.com utopic-updates/universe i386 Packages
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: 
==> default:     
==> default: Err http://us.archive.ubuntu.com utopic-updates/multiverse i386 Packages
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: 
==> default:     
==> default: Err http://us.archive.ubuntu.com utopic-backports/main Sources
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: 
==> default:     
==> default: Err http://us.archive.ubuntu.com utopic-backports/restricted Sources
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: 
==> default:     
==> default: Err http://us.archive.ubuntu.com utopic-backports/universe Sources
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: 
==> default:     
==> default: Err http://us.archive.ubuntu.com utopic-backports/multiverse Sources
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: 
==> default:     
==> default: Err http://us.archive.ubuntu.com utopic-backports/main amd64 Packages
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: 
==> default:     
==> default: Err http://us.archive.ubuntu.com utopic-backports/restricted amd64 Packages
==> default: 
==> default:     
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: 
==> default:     Err http://us.archive.ubuntu.com utopic-backports/universe amd64 Packages
==> default:       404  Not Found [IP: 91.189.91.15 80]
==> default:     Err http://us.archive.ubuntu.com utopic-backports/multiverse amd64 Packages
==> default:       404  Not Found [IP: 91.189.91.15 80]
==> default:     Err http://us.archive.ubuntu.com utopic-backports/main i386 Packages
==> default:       404  Not Found [IP: 91.189.91.15 80]
==> default:     Err http://us.archive.ubuntu.com utopic-backports/restricted i386 Packages
==> default:       404  Not Found [IP: 91.189.91.15 80]
==> default:     Err http://us.archive.ubuntu.com utopic-backports/universe i386 Packages
==> default:       404  Not Found [IP: 91.189.91.15 80]
==> default:     Err http://us.archive.ubuntu.com utopic-backports/multiverse i386 Packages
==> default:       404  Not Found [IP: 91.189.91.15 80]
==> default:     STDERR: W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/main/source/Sources  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/restricted/source/Sources  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/universe/source/Sources  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/multiverse/source/Sources  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/main/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/restricted/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/main/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/universe/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/multiverse/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/universe/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/utopic-security/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.91.23 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/universe/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/main/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/main/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/main/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/restricted/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/universe/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/multiverse/source/Sources  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/main/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/universe/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/utopic-backports/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
==> default:     
==> default:     E: Some index files failed to download. They have been ignored, or old ones used instead.
==> default:     ---- End output of apt-get update ----
==> default:     Ran apt-get update returned 100
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/apt/recipes/default.rb
==> default:     
==> default:      84: execute 'apt-get-update-periodic' do
==> default:      85:   command 'apt-get update'
==> default:      86:   ignore_failure true
==> default:      87:   only_if { apt_installed? }
==> default:      88:   not_if { apt_up_to_date? }
==> default:      89:   notifies :touch, 'file[/var/lib/apt/periodic/update-success-stamp]', :immediately
==> default:      90: end
==> default:      91: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/apt/recipes/default.rb:84:in `from_file'
==> default:     
==> default:     execute("apt-get-update-periodic") do
==> default:       action [:run]
==> default:       ignore_failure true
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :execute
==> default:       command "apt-get update"
==> default:       backup 5
==> default:       returns 0
==> default:       declared_type :execute
==> default:       cookbook_name "apt"
==> default:       recipe_name "default"
==> default:       not_if { #code block }
==> default:       only_if { #code block }
==> default:     end
==> default:     
==> default: 
==> default:   
==> default: * directory[/var/cache/local] action create
==> default: [2016-03-01T21:30:59+00:00] INFO: directory[/var/cache/local] created directory /var/cache/local
==> default:     
==> default: - create new directory /var/cache/local
==> default: [2016-03-01T21:30:59+00:00] INFO: directory[/var/cache/local] owner changed to 0
==> default: [2016-03-01T21:30:59+00:00] INFO: directory[/var/cache/local] group changed to 0
==> default: [2016-03-01T21:30:59+00:00] INFO: directory[/var/cache/local] mode changed to 755
==> default:     
==> default: - change mode from '' to '0755'
==> default:     
==> default: - change owner from '' to 'root'
==> default:     
==> default: - change group from '' to 'root'
==> default: 
==> default: 
==> default:   
==> default: * directory[/var/cache/local/preseeding] action create
==> default: [2016-03-01T21:30:59+00:00] INFO: directory[/var/cache/local/preseeding] created directory /var/cache/local/preseeding
==> default:     
==> default: - create new directory /var/cache/local/preseeding
==> default: [2016-03-01T21:30:59+00:00] INFO: directory[/var/cache/local/preseeding] owner changed to 0
==> default: [2016-03-01T21:30:59+00:00] INFO: directory[/var/cache/local/preseeding] group changed to 0
==> default: [2016-03-01T21:30:59+00:00] INFO: directory[/var/cache/local/preseeding] mode changed to 755
==> default:     
==> default: - change mode from '' to '0755'
==> default:     
==> default: - change owner from '' to 'root'
==> default:     
==> default: - change group from '' to 'root'
==> default: 
==> default: 
==> default:   
==> default: * template[/etc/apt/apt.conf.d/10recommends] action create
==> default: [2016-03-01T21:30:59+00:00] INFO: template[/etc/apt/apt.conf.d/10recommends] created file /etc/apt/apt.conf.d/10recommends
==> default:     
==> default: - create new file /etc/apt/apt.conf.d/10recommends
==> default: [2016-03-01T21:30:59+00:00] INFO: template[/etc/apt/apt.conf.d/10recommends] updated file contents /etc/apt/apt.conf.d/10recommends
==> default:     
==> default: - update content in file /etc/apt/apt.conf.d/10recommends from none to f41e1d
==> default:     
==> default: --- /etc/apt/apt.conf.d/10recommends	2016-03-01 21:30:59.628210967 +0000
==> default:     
==> default: +++ /etc/apt/apt.conf.d/.10recommends20160301-1475-1okmfti	2016-03-01 21:30:59.628210967 +0000
==> default:     
==> default: @@ -1 +1,4 @@
==> default:     
==> default: +# Managed by Chef
==> default:     
==> default: +APT::Install-Recommends "1";
==> default:     
==> default: +APT::Install-Suggests "0";
==> default: [2016-03-01T21:30:59+00:00] INFO: template[/etc/apt/apt.conf.d/10recommends] owner changed to 0
==> default: [2016-03-01T21:30:59+00:00] INFO: template[/etc/apt/apt.conf.d/10recommends] group changed to 0
==> default: [2016-03-01T21:30:59+00:00] INFO: template[/etc/apt/apt.conf.d/10recommends] mode changed to 644
==> default:     
==> default: - change mode from '' to '0644'
==> default:     
==> default: - change owner from '' to 'root'
==> default:     
==> default: - change group from '' to 'root'
==> default: 
==> default: 
==> default:   
==> default: * apt_package[apt-transport-https] action install
==> default:  (up to date)
==> default: Recipe: apache2::default
==> default:   
==> default: * apt_package[apache2] action install
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `install` on resource 'apt_package[apache2]'
==> default:     ================================================================================
==> default:     
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     Expected process to exit with [0], but received '100'
==> default:     ---- Begin output of apt-get -q -y install apache2=2.4.10-1ubuntu1 ----
==> default:     STDOUT: Reading package lists...
==> default:     Building dependency tree...
==> default:     Reading state information...
==> default:     The following extra packages will be installed:
==> default:       apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
==> default:       libaprutil1-ldap liblua5.1-0 ssl-cert
==> default:     Suggested packages:
==> default:       www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom
==> default:       apache2-utils openssl-blacklist
==> default:     The following NEW packages will be installed:
==> default:       apache2 apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
==> default:       libaprutil1-ldap liblua5.1-0 ssl-cert
==> default:     0 upgraded, 9 newly installed, 0 to remove and 1 not upgraded.
==> default:     Need to get 1429 kB of archives.
==> default:     After this operation, 5912 kB of additional disk space will be used.
==> default:     WARNING: The following packages cannot be authenticated!
==> default:       libapr1 libaprutil1 liblua5.1-0 libaprutil1-dbd-sqlite3 libaprutil1-ldap
==> default:       apache2-bin apache2-data apache2 ssl-cert
==> default:     STDERR: E: There are problems and -y was used without --force-yes
==> default:     ---- End output of apt-get -q -y install apache2=2.4.10-1ubuntu1 ----
==> default:     Ran apt-get -q -y install apache2=2.4.10-1ubuntu1 returned 100
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/apache2/recipes/default.rb
==> default:     
==> default:      21: package 'apache2' do
==> default:      22:   package_name node['apache']['package']
==> default:      23: end
==> default:      24: 
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/apache2/recipes/default.rb:21:in `from_file'
==> default:     
==> default:     apt_package("apache2") do
==> default:       package_name "apache2"
==> default:       action [:install]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :package
==> default:       cookbook_name "apache2"
==> default:       recipe_name "default"
==> default:     end
==> default:     
==> default: 
==> default: [2016-03-01T21:31:02+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2016-03-01T21:31:02+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: 
==> default: [2016-03-01T21:31:02+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 4 resources updated in 01 minutes 52 seconds
==> default: [2016-03-01T21:31:02+00:00] INFO: Sending resource update report (run-id: ae4e7c3d-9b81-45b7-95c4-8060d795c949)
==> default: [2016-03-01T21:31:03+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-03-01T21:31:03+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-03-01T21:31:03+00:00] ERROR: apt_package[apache2] (apache2::default line 21) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install apache2=2.4.10-1ubuntu1 ----
==> default: STDOUT: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
==> default:   libaprutil1-ldap liblua5.1-0 ssl-cert
==> default: Suggested packages:
==> default:   www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom
==> default:   apache2-utils openssl-blacklist
==> default: The following NEW packages will be installed:
==> default:   apache2 apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
==> default:   libaprutil1-ldap liblua5.1-0 ssl-cert
==> default: 0 upgraded, 9 newly installed, 0 to remove and 1 not upgraded.
==> default: Need to get 1429 kB of archives.
==> default: After this operation, 5912 kB of additional disk space will be used.
==> default: WARNING: The following packages cannot be authenticated!
==> default:   libapr1 libaprutil1 liblua5.1-0 libaprutil1-dbd-sqlite3 libaprutil1-ldap
==> default:   apache2-bin apache2-data apache2 ssl-cert
==> default: STDERR: E: There are problems and -y was used without --force-yes
==> default: ---- End output of apt-get -q -y install apache2=2.4.10-1ubuntu1 ----
==> default: Ran apt-get -q -y install apache2=2.4.10-1ubuntu1 returned 100
==> default: [2016-03-01T21:31:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by svanzoest** [comment]
Utopic 14.10 is End of Lifed see https://lists.ubuntu.com/archives/ubuntu-announce/2015-July/000197.html. You will need to update to a newer version of Ubuntu. The current releases of Ubuntu are https://wiki.ubuntu.com/Releases

**Comment by myeonghakim** [comment]
Is that possible to override shell command "apt-get -q -y install apache2=2.4.7-1ubuntu4.8" to "apt-get -q -y install apache2" in ubuntu? I think it's an error in my case. Target vm type is an Ubuntu 14.04LTS, and bootstrap package is apche2(3.1.0). Also this command is an error too. "E: Failed to fetch http://ftp.daum.net/ubuntu/pool/main/a/apache2/apache2_2.4.7-1ubuntu4.8_amd64.deb  404  Not Found" . That url is correct, but filename is deprecated. Actually updated filename is apache2_2.4.7-1ubuntu4.9_amd64.deb. So i want to override shell command like this "apt-get -q -y install apache2". I don't wanna specific package version.

**Comment by svanzoest** [comment]
Peter, looks like you need to use the `apt` cookbook and update your apt
package list. You can do this manually by running `apt-get update`.
