### ISSUE TITLE
drupal-cookbook drush installation fails due to mod_php5 apache2 version 5.4

### ISSUE THREAD

**Issue by sernapallyanurag** [svanzoest-cookbooks/apache2#413]
============================================================================
====
    Error executing action `run` on resource 'execute[download_drupal]'
    ============================================================================
====

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of  /usr/local/bin/drush dl drupal --drupal-project-rename
=drupal -y ----
    STDOUT:
    STDERR: Your command line PHP installation is too old. Drush requires at
 [error]
    least PHP 5.5.0. To suppress this check, set the environment variable
    DRUSH_NO_MIN_PHP=1
    ---- End output of  /usr/local/bin/drush dl drupal --drupal-project-rename=d
rupal -y ----
    Ran  /usr/local/bin/drush dl drupal --drupal-project-rename=drupal -y return
ed 1

How do I install Latest PHP version? Where do I make changes?

**Comment by svanzoest** [comment]
Hi there,

The installation of packages comes via the chef `package` resource and therefore the package installed would be the latest as it were provided by the package manager. If you would want to install a newer version of the mod_php5 package for example, you would need to make sure that the package manager (`apt`,`yum`,`zypper`) has the expected version of the package available.

The cookbook simply installs the latest version available via the package manager provided by the operating system.

**Comment by sernapallyanurag** [comment]
The Yum package for mod_php 5.6 is available but chef installs the previous version 5.4.

**Comment by sernapallyanurag** [comment]
Hi,
I am unable to install Drush since the error above shows that the PHP-cli version is old. But that is the latest available version for centos as you rightly mentioned.
I even tried to suppress using the Environment variable clue given in the error but no luck.
Can you suggest me a work around?

**Comment by svanzoest** [comment]
Add a package repository to centos that has the right version you want. You
can do this via the yum cookbooks.

**Comment by svanzoest** [comment]
@sernapallyanurag I am not sure what more we can do here, maybe it is best to reach out to the drupal cookbook maintainer if installing a newer version of the php package does not resolve the issue you are having.
