### ISSUE TITLE
reload not working centOs 6.x and apache 2.4

### ISSUE THREAD

**Issue by tb01923** [svanzoest-cookbooks/apache2#423]
I am trying to install onto centOs 6.4 and apache 2.4 version.  I have the following attributes:
```
{
  "apache": {
    "package": "httpd24",
    "devel_package": "httpd24-devel",
    "service_name": "httpd24-httpd",
    "dir": "/opt/rh/httpd24",
    "conf_dir": "/opt/rh/httpd24"
  }
} 
```
and it looks like everything is going on ok.  service enable fizzles out.  running this I see the folowing in the console:

```
Recipe: apache2::default
  * service[apache2] action enable
    
    ================================================================================
    Error executing action `enable` on resource 'service[apache2]'
    ================================================================================
    
    Errno::ENOENT
    -------------
    No such file or directory - /usr/sbin/httpd
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/apache2/recipes/default.rb
    
    206: service 'apache2' do
    207:   service_name apache_service_name
    208:   case node['platform_family']
    209:   when 'rhel'
    210:     if node['platform_version'].to_f < 7.0
    211:       restart_command "/sbin/service #{apache_service_name} restart && sleep 1"
    212:       reload_command "/sbin/service #{apache_service_name} graceful && sleep 1"
    213:     end
    214:   when 'debian'
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/apache2/recipes/default.rb:206:in `from_file'
    
    service("apache2") do
      action [:enable, :start]
      supports {:restart=>true, :reload=>true, :status=>true, :start=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "httpd24-httpd"
      pattern "apache2"
      restart_command "/sbin/service httpd24-httpd restart && sleep 1"
      reload_command "/sbin/service httpd24-httpd graceful && sleep 1"
      declared_type :service
      cookbook_name "apache2"
      recipe_name "default"
      only_if "/usr/sbin/httpd -t"
    end
    
    Platform:
    ---------
    x86_64-linux
```

Further all the service commands work except graceful:
```
$ sudo service httpd24-httpd graceful
/opt/rh/httpd24/root/usr/sbin/apachectl: line 116: /usr/bin/systemctl: No such file or directory
```

I dont know where esle to poke around...  Any hints appreciated

**Comment by svanzoest** [comment]
The apache package generally assumes you are using the standard package provided by the operating system. The attributes such as `apache.dir` should match the package your are installing. Are you doing your own rpm?

**Comment by tb01923** [comment]
I don't think so.  I do install the repo prior to kicking the coobook off: 
```
http://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo
```
without that, the cookbook cannot find httpd24.  Then there are various failures of the cookbook driving me to use the package name, and then subsequent failures about locations that make things fail without me overriding those attributes.  For example - the install defaults to /etc/httpd for a lot of things, but httpd24 isn't getting installed by the package. 

My wrapper cookbook currently is: 
```
bash 'yum install epel-httpd24' do
  cwd '/etc/yum.repos.d/'
  code <<-EOH
     cd /etc/yum.repos.d/
     wget http://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo
  EOH
   not_if { ::File.exists?('/etc/yum.repos.d/epel-httpd24.repo') }
end

include_recipe 'apache2::default'
```

**Comment by tb01923** [comment]
Well I tried to install httpd24 by hand on a fresh VM (centOS 6):
```
 cd /yum/repos.d
 wget http://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo
sudo yum install httpd24
```
And it worked to the same degree as the cookbok.  Then running: 

```
sudo service httpd24-httpd graceful
/opt/rh/httpd24/root/usr/sbin/apachectl: line 116: /usr/bin/systemctl: No such file or directory
```

It doesn't look to be associated with the cookbook at all. It looks tobe completely associated with the httpd24 install.  I wonder if a solution is to remove the graceful section of the cookbook and defer to a restart for now?

**Comment by tb01923** [comment]
I posted on serverfault.com trying to chase this down from a non-cookbook basis (linux/apache) [here](     http://serverfault.com/questions/771843/centos-apache24?noredirect=1#comment973308_771843).  Unfortunately this is their reply:

```
I reproduced it. Don't use "graceful" command for it. Try to use sudo service httpd24-httpd start or sudo service httpd24-httpd restart – Anton ...
```

The offending lines of code come from: https://github.com/svanzoest-cookbooks/apache2/blob/master/recipes/default.rb

```
service 'apache2' do
  service_name apache_service_name
  case node['platform_family']
  when 'rhel'
    if node['platform_version'].to_f < 7.0
      restart_command "/sbin/service #{apache_service_name} restart && sleep 1"
      reload_command "/sbin/service #{apache_service_name} graceful && sleep 1"
    end
  when 'debian'
    provider Chef::Provider::Service::Debian
  when 'arch'
    service_name apache_service_name
  end
  supports [:start, :restart, :reload, :status]
  action [:enable, :start]
  only_if "#{node['apache']['binary']} -t", :environment => { 'APACHE_LOG_DIR' => node['apache']['log_dir'] }, :timeout => 10
end
```
I think the recommendation is to change this line - since garceful and http24 on centos6 doesn't work: 
```
      reload_command "/sbin/service #{apache_service_name} graceful && sleep 1"
```
or maybe just remove it (i am not a chef expert)?  Any thoughts on how to proceed here - I am happy to do what is recommended (including fork, fix, pull).

**Comment by tb01923** [comment]
I created a fork/pull to address this: https://github.com/svanzoest-cookbooks/apache2/pull/424 seems to be working for me...

**Comment by svanzoest** [comment]
So it looks like you are using a custom backport package that we currently do not support. The cookbook is developed to support the native httpd, which currently is apache 2.2 on centos 6.

However, via https://www.softwarecollections.org/en/scls/rhscl/httpd24/ you can install the httpd24 package, which looks to be a backport of the centos 7 version.

The changes you are making in #424 seem to mostly revolve around using systemd and httpd24. To enable apache 2.4 behavior you would set `apache.version` to `2.4`.  That should be alll that is needed assuming everything else stays the same.

The only thing is that there are still guards that are specific to what version of the `rhel` platform family your are using that may cause issues. We could adjust that to allow for version 6 of `rhel` with `apache.version` set to `2.4`.

It seems to me that would get you the behavior you are looking for based on the PR you provided.
