### ISSUE TITLE
Httpd -t timeout option - possible PR

### ISSUE THREAD

**Issue by goncalopereira** [svanzoest-cookbooks/apache2#426]
Hello,
I'm currently using this cookbook but getting issues using the service resource as the ten second timeout is too small for my production setup.

I've currently monkey-patched the service resource as follows for reference but if you agree I'll do a PR with timeout as a option (plus tests) so I can remove this ugly fix?

```
chef_gem "chef-rewind" do
  compile_time true
end
require 'chef/rewind'
include_recipe 'apache2'
unwind "service[apache2]"
service 'apache2' do
  service_name node['apache']['service_name']
  restart_command '/sbin/service httpd restart && sleep 1' if node['apache']['version'] == '2.2'
  reload_command '/sbin/service httpd graceful'
  supports [:start, :restart, :reload, :status]
  action [:enable, :start]
  timeout 600
  only_if "#{node['apache']['binary']} -t", :environment => { 'APACHE_LOG_DIR' => node['apache']['log_dir'] }, :timeout => 600
end

```

**Comment by svanzoest** [comment]
A 10 second timeout is very long, if you need more time then that it usually means something else is taking a lot longer than it should. I would investigate that and see what is taking so long.

**Comment by goncalopereira** [comment]
Thank you for your comment - I agree with that but we have a lot of rewrites and configs due to a third party CMS :) Our 'httpd -t' takes about 20 seconds. Unfortunately it is out of our control.

**Comment by svanzoest** [comment]
The most common delay is not setting a FQDN, so apache httpd spends a lot of time determining a valid hostname. I would at least check to see how long that takes or if there is anything in the logs that point out why it is taking so long.

**Comment by goncalopereira** [comment]
Not being able to reproduce the issue in our CI after a few days so I'm going to take your suggestion. Thank you.
