### ISSUE TITLE
How do I add FilesMatch and AddHandler parameters to web_app.conf.erb?

### ISSUE THREAD

**Issue by sernapallyanurag** [svanzoest-cookbooks/apache2#431]
HI,

I am trying to configure Vhost for Bugzilla. 
``
<VirtualHost *:80>
DocumentRoot /var/www/html/bugzilla/
</VirtualHost>
<Directory /var/www/html/bugzilla>
AddHandler cgi-script .cgi
Options +Indexes +ExecCGI
DirectoryIndex index.cgi
AllowOverride Limit FileInfo Indexes
</Directory>
``

This is the minimal configuration required. I am able to add all parameters except AddHandler.

``
<% if @params[:add_handler] -%>
  AddHandler <%= [@params[:add_handler]].flatten.join " " %>
  <% end -%>
``
Will this work?

**Comment by svanzoest** [comment]
I would pass in your own template:
````
web_app "bugzilla" do
   template 'bugzilla.conf.erb'
   server_name 'bugzilla.mydomain.com'
   docroot "/var/www/html/bugzilla/"
end
````
and pass in `bugzilla.conf.erb` that looks more a long the lines of
````
<VirtualHost *:<%= @params[:server_port] %>>
  ServerName <%= @params[:server_name] %>
  DocumentRoot <%= @params[:docroot] %>
  <Directory <%= @params[:docroot] %>>
     AddHandler cgi-script .cgi Options +Indexes +ExecCGI 
     DirectoryIndex index.cgi 
     AllowOverride Limit FileInfo Indexes 
  </Directory> 
  ErrorLog <%= node['apache']['log_dir'] %>/<%= @params[:name] %>-error.log
  CustomLog <%= node['apache']['log_dir'] %>/<%= @params[:name] %>-access.log combined
</VirtualHost> 
```

**Comment by sernapallyanurag** [comment]
Thank you. I was using default template name. changing the name was key.

``
<VirtualHost *:<%= @params[:server_port] %>>
  ServerName <%= @params[:server_name] %>
  <% if @params[:server_aliases] -%>
  ServerAlias <%= @params[:server_aliases].join " " %>
  <% end -%>
  DocumentRoot <%= @params[:docroot] %>
  <Directory <%= @params[:docroot] %>>
     AddHandler cgi-script .cgi 
	 Options +Indexes +ExecCGI +FollowSymLinks
     DirectoryIndex index.cgi 
     AllowOverride All FileInfo Indexes 
	 Require all granted
  </Directory> 
  ErrorLog <%= node['apache']['log_dir'] %>/<%= @params[:name] %>-error.log
  CustomLog <%= node['apache']['log_dir'] %>/<%= @params[:name] %>-access.log combined
</VirtualHost> 
``
