### ISSUE TITLE
adding params or variables to apache_conf template

### ISSUE THREAD

**Issue by toski1** [svanzoest-cookbooks/apache2#434]
Hi,

I am trying to enable mod_proxy_balancer and pass variables to the template specific to the configuration I require, however the variables do not seem to be passing to the template.  In the template I have tried nearly every variation of @params or @key_name but they always evaluate to nil.  Any suggestion?

```
apache_conf 'mod_proxy_balancer' do
  source 'etc/httpd/conf.d/mod_proxy_balancer.conf.erb'
  enable true
  variables(
    :store_nodes => store_nodes,
    :admin_nodes => admin_nodes,
    :search_nodes => search_nodes,
    :n_increment => 1
  )
end
```

OR trying @params

```
apache_conf 'mod_proxy_balancer' do
  source 'etc/httpd/conf.d/mod_proxy_balancer2.conf.erb'
  enable true
  store_nodes store_nodes
  admin_nodes admin_nodes
  search_nodes search_nodes
end
```

**Comment by svanzoest** [comment]
Only `web_app` supports `params` as a way to pass in parameters. The templates by any of the other definitions generally directly grab node attributes. It is good to note, however, that we do not support that at the moment. I do not think there has been a need.

In most cases you will want to configure the proxy for a particular vhost and not the web server as a whole. Looking at http://httpd.apache.org/docs/current/mod/mod_proxy_balancer.html they do not have any directives that you would want to configure globally, it is best to configure them using `web_app` or by grabbing the node attributes directly in your template.

**Comment by toski1** [comment]
Hi scanzoest - thank you
I got around this by adding this one line to the apache_conf defintition

`variables params[:variables] if params[:variables]`

I can then pass variables to these templates by calling @variables[:key_name] in the template.  I've very much needed this functionality as I am using the cookbook for a large eCommerce frontend tier.

**Comment by svanzoest** [comment]
sure, you can do that, but what exactly are you setting in the variables? I am not against adding functionality, I am just trying to understand the use case.

**Comment by toski1** [comment]
Hi svanzoest
I am creating load balancer pools and passing in chef search results for nodes of specific types along with their associated attributes.  This is specific to application configuration (ports, cluster ID's) relative to the nodes returned in the search.

**Comment by svanzoest** [comment]
Okay, in that case I would pass those into `web_app` or if you really want to create a glob, non-vhost specific proxy, I would grab the application configuration in the _erb_ with `node['store_nodes']` attributes.
