### ISSUE TITLE
enable mod_proxy_ajp issue

### ISSUE THREAD

**Issue by toski1** [svanzoest-cookbooks/apache2#437]
Hoping you can help me solve a bit of a challenge.

I use wrapper cookbooks to add any customization to a community cookbook that we depend.  In my wrapper, I am trying to change the proxy.conf file that you load as a result of calling apache2::mod_proxy_ajp

The problem is, it will load the default proxy.conf template, then load the updated proxy.conf template from the wrapper cookbook, resulting in a change to the configuration which will restart apache.  I cannot have Apache2 restarting every 30 mins in the prod environment.

I tried:
`apache_mod 'proxy' do
source 'etc/httpd/conf.d/mod_proxy.conf.erb'
enable true
conf false
end
apache_module 'proxy_ajp'
apache_module 'proxy_http'`

Bu this results in:
`root@devvm:/home/vagrant# /etc/init.d/apache2 restart
apache2: Syntax error on line 106 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/proxy_ajp.load: Cannot load /usr/lib/apache2/modules/mod_proxy_ajp.so into server: /usr/lib/apache2/modules/mod_proxy_ajp.so: undefined symbol: proxy_module
Action 'configtest' failed.
The Apache error log may have more information.
 failed!
`

**Comment by toski1** [comment]
Sorry I solved this because I was calling apache_mod 'proxy' instead of the correct apache_module 'proxy'

**Comment by drpebcak** [comment]
Glad you got it solved!
