### ISSUE TITLE
chef apache error in chef-client

### ISSUE THREAD

**Issue by swathi0701** [svanzoest-cookbooks/apache2#438]
================================================================================
    Error executing action `start` on resource 'service[httpd]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/bin/systemctl --system start httpd ----
    STDOUT:
    STDERR: Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.
    ---- End output of /usr/bin/systemctl --system start httpd ----
    Ran /usr/bin/systemctl --system start httpd returned 1

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/apache/recipes/default.rb

     34: service "httpd" do
     35:        supports [:restart, :reload, :status]
     36:        action [:enable, :start]
     37: end
     38:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/apache/recipes/default.rb:34:in `from_file'

    service("httpd") do
      action [:enable, :start]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "httpd"
      enabled true
      pattern "httpd"
      declared_type :service
      cookbook_name "apache"
      recipe_name "default"
    end

    Platform:
    ---------
    x86_64-linux

Running handlers:
[2016-07-30T14:47:07+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-07-30T14:47:07+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 07 seconds
[2016-07-30T14:47:08+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-30T14:47:08+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-30T14:47:08+00:00] ERROR: service[httpd] (apache::default line 34) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system start httpd ----
STDOUT:
STDERR: Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.
---- End output of /usr/bin/systemctl --system start httpd ----
Ran /usr/bin/systemctl --system start httpd returned 1
[2016-07-30T14:47:08+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by svanzoest** [comment]
You will need to debug it and figure out why apache2 gave an error exit
status. See "systemctl status httpd.service" and "journalctl -xe" for
details.
