### ISSUE TITLE
Apache 2.2 install has no <Directory /> security

### ISSUE THREAD

**Issue by driskell** [svanzoest-cookbooks/apache2#444]
I was testing a cookbook across a 2.2 and a 2.4 and noticed differences in behaviour due to a missing Allow directive. In 2.4 it would not work, it 2.2 it would.

It seems that the httpd.conf for 2.4 contains a lock down as expected for <Directory /> - however, 2.2 does not.

Is there a reason for this? Would you accept a pull request to make 2.2 safe-by-default? I guess my concern is this could now be a breaking change if other people are now relying on insecure defaults with 2.2.

Thanks!

**Comment by svanzoest** [comment]
The 2.4 version is stricter and over time the 2.2 support will be deprecated. The reason for 2.2 be less strict is mostly because we did not want to break backwards compatibility for a cookbook that had been in the wild for such a long time. It was best to apply these best practices going forward only.

So, yes, it would be breaking change and since the focus is fully on 2.4 now, I think it is more appropriate for people to upgrade then implement additional features and improvements for the legacy 2.2 branch.

**Comment by driskell** [comment]
Hey @svanzoest, thanks for taking the time to respond.

I found it very surprising that the lock down was not there and it was a default, "everything open", configuration. I wonder if the best approach is to warn people of this. There is no mention of deprecation of 2.2 in the README nor of the missing lock down and the difference to 2.4 so maybe it could be done as part of adding something around that?

I can appreciate the view that the lock down might be just best practices, but from my own standpoint it's of my opinion that it's a security issue as it breaks the "secure out of the box" / "secure by default" principle, and furthermore to anyone I know is an unexpected outcome.

I'm happy to help and wondering if a PR for something like the following would be acceptable? Happy to discuss.

# Add a configurable option, `enable_strict_2.2`, that puts in the same 2.4 lock down but in 2.2 syntax. This should keep backwards compatibility. It's essentially what I do now but by using a wrapper cookbook instead of an attribute
# Add a Known Issues section underneath Usage. This can outline that the usual <Directory /> is not there by default in 2.2 to maintain backwards compatible, and that it recommended that new users set `enable_strict_2.2`. This could be used to add extra important bits in the future too.
# Expand Attributes section node['apache']['version'] a little to state that 2.2 support is currently best-effort and will be deprecated over time. Also add in documentation for `enable_strict_2.2`

Does this seem OK or do you think too intrusive?
