### ISSUE TITLE
AH00534: apache2: Configuration error: No MPM loaded.

### ISSUE THREAD

**Issue by maneeshmp** [svanzoest-cookbooks/apache2#445]
I am getting below error after installing apache through chef

~$ sudo service apache2 restart
 * Restarting web server apache2                                                                                                                              [fail]
 * The apache2 configtest failed.
Output of config test was:
AH00534: apache2: Configuration error: No MPM loaded.
Action 'configtest' failed.
The Apache error log may have more information.

cookbook version : 3.2.2
Platform: Ubuntu 14.04 

My Recipe has below content

include_recipe 'apache2::default'
include_recipe 'apache2::mod_ssl'
include_recipe 'apache2::mod_proxy_http'
include_recipe 'apache2::mod_headers'
include_recipe 'apache2::mod_proxy'
include_recipe 'apache2::mpm_prefork'

Attributes file has below values defined,

default['apache']['version'] = '2.4.7'
default['apache']['mpm']  = "event"

**Comment by drpebcak** [comment]
@maneeshmp are you attempting to use two MPMs on purpose?

**Comment by maneeshmp** [comment]
No I am not,  I included it to see if the error will go away

include_recipe 'apache2::mpm_prefork'

**Comment by drpebcak** [comment]
Ok, so are you trying to use prefork or event?

Also, the `apache.version` attribute is really only used to differentiate between 2.2 and 2.4... on ubuntu 14.04 you shouldn't have to override it, it's already set to 2.4.

**Comment by maneeshmp** [comment]
I actually need only below things,

include_recipe 'apache2::default'
include_recipe 'apache2::mod_ssl'
include_recipe 'apache2::mod_proxy_http'

Remaining things were added to see if the error would go away.

**Comment by drpebcak** [comment]
Hmm.. ok. So the default MPM for 14.04 is event. Are you installing the default package, or are you getting it from a custom location?

If you do `apache2ctl -V` does it say which MPM it wants to use?

**Comment by svanzoest** [comment]
@maneeshmp just specifying

```
include_recipe 'apache2::default'
include_recipe 'apache2::mod_ssl'
include_recipe 'apache2::mod_proxy_http'
```

should be fine because we pull in `apache::mod_proxy` from within `apache2:mod_proxy_http`, but I would define that explicitly just in case.

Are you experiencing any errors with including the following recipes in your wrapper cookbook as follows?
```
include_recipe 'apache2::default'
include_recipe 'apache2::mod_ssl'
include_recipe 'apache2::mod_proxy'
include_recipe 'apache2::mod_proxy_http'
```

**Comment by maneeshmp** [comment]
sorry I did not respond to this question.  After getting the error, I rewrote my recipe using package resource and exec resource(for a2enmod).I will check and update here
