### ISSUE TITLE
Apache failed when restarting the first time

### ISSUE THREAD

**Issue by tobymaro** [svanzoest-cookbooks/apache2#446]
Hello,

I have installed apache2 on Centos 7.2. And now I see error:

Sep 19 11:37:40 mr-spark-lb httpd[3494]: [Mon Sep 19 11:37:40.258315 2016] [core:warn] [pid 3494] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
Sep 19 11:37:40 mr-spark-lb httpd[3494]: [Mon Sep 19 11:37:40.258905 2016] [core:warn] [pid 3494] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
Sep 19 11:37:40 mr-spark-lb httpd[3494]: (2)No such file or directory: AH02291: Cannot access directory '/etc/httpd/${APACHE_LOG_DIR}/' for error log of vhost defined at /etc/httpd/site...parklb.conf:1
Sep 19 11:37:40 mr-spark-lb httpd[3494]: AH00014: Configuration check failed

Please advise.

**Comment by svanzoest** [comment]
how are you running the config check? are you using `/usr/sbin/apachectl configtest`?
