### ISSUE TITLE
setting default["apache"]["version"] = "2.4" does not work

### ISSUE THREAD

**Issue by sbalaram** [svanzoest-cookbooks/apache2#448]
we are on redhat-release-server-6Server-6.8.0.5.el6.x86_64 and it installs apache2.4 but with 2.2 configuration files.  

in apache2/attributes/default.rb  Line 57 there is no condition for >=6.0 and it defaults to 2.2

this causes these issues:

Invalid command 'LockFile', perhaps misspelled or defined by a module not included in the server configuration

httpd: Syntax error on line 106 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/mods-enabled/authz_default.load: Cannot load /usr/lib64/httpd/modules/mod_authz_default.so into server: /usr/lib64/httpd/modules/mod_authz_default.so: cannot open shared object file:
 No such file or directory

Invalid command 'LockFile', perhaps misspelled or defined by a module not included in the server configuration

did anyone had these issues ?

shall I submit a PR to add that condition to support for RHEL 6.0 ?

please advise we are blocked by this and we dont want one more wrapper cookbook just for this fix  ?

**Comment by svanzoest** [comment]
What version of apache2 is getting installed? Rhel 6 shipped with 2.2. you
can not just change the apache.version to have it install 2.4.

**Comment by sbalaram** [comment]
Server version: Apache/2.4.20 (Unix) is getting installed.   RHEL was not shipped with 2.2 and we are trying to install 2.4

**Comment by drpebcak** [comment]
https://access.redhat.com/solutions/445713

**Comment by sbalaram** [comment]
yes the article shows but  checked again on our hosts and none of them have 2.2

**Comment by svanzoest** [comment]
@sbalaram when you run the cookbook it will install `apache.package` which on `redhat` is `httpd` via yum. The errors you are seeing above in the show 2.2 directives. In 2.4 `LockFile` is now `Mutex` and there is no `mod_authz_default` in 2.4, as it is replaced by `mod_authz_core`. 

This suggests to me that are either not setting `apache.version` to `2.4` early enough or not at all, as the cookbook is behaving as if `apache.version` was not set to `2.4` when the cookbook ran.

**Comment by sbalaram** [comment]
thanks @svanzoest the attribute was not set early enough was the issue, re-arranged the recipe include and it was all good
